spring:
  application:
    name: eureka-consumer-ribbon-hystrix

server:
  port: 2101

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:1001/eureka/

management:
  endpoints:
    web:
      exposure:
        #actuator监控对外暴露hystrix.stream端点，默认情况下，只会暴露health和info端点
        include: health, info, hystrix.stream
